import {Transformer} from "./Transformer";
import {EOL} from "os";
/**
 * Created by amatsegor on 5/4/17.
 */

export class DartTemplateTransformer implements Transformer {
    transformComment(comment) {
        return "  // " + comment;
    }

    transformKeyValue(key, value) {
        var normalizedValue = value.replace(/%newline%/gi, "\\n");
        normalizedValue = normalizedValue.replace(/"/gi, '\\"');
        normalizedValue = normalizedValue.replace(/%([@df])/gi, '%$1');
        normalizedValue = normalizedValue.replace(/%s/gi, "%@");

        return '  String get ' + key + ' => get("' + key + '");';
    }

    static AUTOGENERATED_TAG: '// AUTO-GENERATED'

    insert(input, newValues, options) {
        if (!input) {
            input = '';
        }

        var generatedIndex = input.indexOf(DartTemplateTransformer.AUTOGENERATED_TAG);
        if (generatedIndex >= 0) {
            input = input.substr(0, generatedIndex);
        }

        var className = options && options.className ? options.className : 'T';
        var header = options && options.header ? options.header : 'library core.t';
        var baseClass = options && options.baseClass ? options.baseClass : 'TranslationSet';

        var output = input + DartTemplateTransformer.AUTOGENERATED_TAG + EOL +
            header + EOL + EOL +
            'class ' + className + ' extends ' + baseClass + ' { ' + EOL + EOL +
            '  ' + className + '(values): super(values);' + EOL + EOL +
            newValues + EOL +
            '}';

        return output;
    }
}
;