"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var os_1 = require("os");
/**
 * Created by amatsegor on 5/4/17.
 */
var DartTemplateTransformer = (function () {
    function DartTemplateTransformer() {
    }
    DartTemplateTransformer.prototype.transformComment = function (comment) {
        return "  // " + comment;
    };
    DartTemplateTransformer.prototype.transformKeyValue = function (key, value) {
        var normalizedValue = value.replace(/%newline%/gi, "\\n");
        normalizedValue = normalizedValue.replace(/"/gi, '\\"');
        normalizedValue = normalizedValue.replace(/%([@df])/gi, '%$1');
        normalizedValue = normalizedValue.replace(/%s/gi, "%@");
        return '  String get ' + key + ' => get("' + key + '");';
    };
    DartTemplateTransformer.prototype.insert = function (input, newValues, options) {
        if (!input) {
            input = '';
        }
        var generatedIndex = input.indexOf(DartTemplateTransformer.AUTOGENERATED_TAG);
        if (generatedIndex >= 0) {
            input = input.substr(0, generatedIndex);
        }
        var className = options && options.className ? options.className : 'T';
        var header = options && options.header ? options.header : 'library core.t';
        var baseClass = options && options.baseClass ? options.baseClass : 'TranslationSet';
        var output = input + DartTemplateTransformer.AUTOGENERATED_TAG + os_1.EOL +
            header + os_1.EOL + os_1.EOL +
            'class ' + className + ' extends ' + baseClass + ' { ' + os_1.EOL + os_1.EOL +
            '  ' + className + '(values): super(values);' + os_1.EOL + os_1.EOL +
            newValues + os_1.EOL +
            '}';
        return output;
    };
    return DartTemplateTransformer;
}());
exports.DartTemplateTransformer = DartTemplateTransformer;
;
