"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var os_1 = require("os");
/**
 * Created by amatsegor on 5/4/17.
 */
var iOSTransformer = (function () {
    function iOSTransformer() {
    }
    iOSTransformer.prototype.transformComment = function (comment) {
        return "// " + comment;
    };
    iOSTransformer.prototype.transformKeyValue = function (key, value) {
        var normalizedValue = value.replace(/%newline%/gi, "\\n");
        normalizedValue = normalizedValue.replace(/"/gi, '\\"');
        normalizedValue = normalizedValue.replace(/%([@df])/gi, '%$1');
        normalizedValue = normalizedValue.replace(/%s/gi, "%@");
        return '"' + key + '" = "' + normalizedValue + '";';
    };
    iOSTransformer.prototype.insert = function (input, newValues) {
        if (!input) {
            input = '';
        }
        var generatedIndex = input.indexOf(iOSTransformer.AUTOGENERATED_TAG);
        if (generatedIndex >= 0) {
            input = input.substr(0, generatedIndex);
        }
        return input + iOSTransformer.AUTOGENERATED_TAG + os_1.EOL + newValues;
    };
    return iOSTransformer;
}());
exports.iOSTransformer = iOSTransformer;
