import {Transformer} from "./Transformer";
import {EOL} from "os";
/**
 * Created by amatsegor on 5/4/17.
 */

export class iOSTransformer implements Transformer {

    transformComment(comment: string) {
        return "// " + comment;
    }

    transformKeyValue(key: string, value: string) {
        let normalizedValue = value.replace(/%newline%/gi, "\\n");
        normalizedValue = normalizedValue.replace(/"/gi, '\\"');
        normalizedValue = normalizedValue.replace(/%([@df])/gi, '%$1');
        normalizedValue = normalizedValue.replace(/%s/gi, "%@");

        return '"' + key + '" = "' + normalizedValue + '";';
    }

    static AUTOGENERATED_TAG: '// AUTO-GENERATED';

    insert(input: string, newValues: string) {
        if (!input) {
            input = '';
        }

        let generatedIndex = input.indexOf(iOSTransformer.AUTOGENERATED_TAG);
        if (generatedIndex >= 0) {
            input = input.substr(0, generatedIndex);
        }

        return input + iOSTransformer.AUTOGENERATED_TAG + EOL + newValues;
    }
}